spring:
  profiles:
    active: dev
  redis:
    host: 139.199.20.39
    port: 6666

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.upc.api.bean
  mapper-locations: classpath:mapper/*.xml

