eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: ${EUREKA}

server:
  port: 8867

spring:
  application:
    name: water-api

  datasource:
    username: waiter
    password: liulaoshidatabase
    url: jdbc:mysql://139.199.20.39:3306/water_cloud?characterEncoding=utf8&useSSL=false

management:
  endpoints:
    web:
      exposure:
        include: '*'

