eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka

server:
  port: 8866

spring:
  application:
    name: water-security
  datasource:
    username: waiter
    password: liulaoshidatabase
    url: jdbc:mysql://139.199.20.39:3306/water_cloud_security?characterEncoding=utf8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.security: debug
